CREATE TABLE IF NOT EXISTS `starter_pack_claims` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `identifier` VARCHAR(50) NOT NULL UNIQUE,
    `claimed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
